<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34209" started-at="2017-01-02T10:36:22Z" finished-at="2017-01-02T10:36:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34209" started-at="2017-01-02T10:36:22Z" finished-at="2017-01-02T10:36:56Z">
      <class name="Test.com.test.baseclass$DataProviderTest">
        <test-method status="PASS" signature="Chrome_setup()[pri:0, instance:Test.com.test.baseclass$DataProviderTest@39c0f4a]" name="Chrome_setup" is-config="true" duration-ms="5322" started-at="2017-01-02T16:06:22Z" finished-at="2017-01-02T16:06:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Chrome_setup -->
        <test-method status="PASS" signature="SuccessfullLogin(java.lang.String, java.lang.String)[pri:0, instance:Test.com.test.baseclass$DataProviderTest@39c0f4a]" name="SuccessfullLogin" duration-ms="11503" started-at="2017-01-02T16:06:27Z" data-provider="validcredentials" finished-at="2017-01-02T16:06:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[rishav171]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qwerty1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SuccessfullLogin -->
        <test-method status="FAIL" signature="Faliedlogin(java.lang.String, java.lang.String)[pri:0, instance:Test.com.test.baseclass$DataProviderTest@39c0f4a]" name="Faliedlogin" duration-ms="15042" started-at="2017-01-02T16:06:39Z" data-provider="invalidcredentials" finished-at="2017-01-02T16:06:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[testuser]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qwerty1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ Invalid username or Password ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  Invalid username or Password 
	at org.testng.Assert.fail(Assert.java:94)
	at Test.com.test.login.verifyLoginSuccess(login.java:91)
	at Test.com.test.baseclass$DataProviderTest.Faliedlogin(baseclass.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Faliedlogin -->
        <test-method status="PASS" signature="shutDownSelenium()[pri:0, instance:Test.com.test.baseclass$DataProviderTest@39c0f4a]" name="shutDownSelenium" is-config="true" duration-ms="2315" started-at="2017-01-02T16:06:54Z" finished-at="2017-01-02T16:06:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDownSelenium -->
      </class> <!-- Test.com.test.baseclass$DataProviderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
